generate:
	dia -e kasitekaavio.svg kasitekaavio.dia
	convert kasitekaavio.svg kasitekaavio.pdf
	rm kasitekaavio.svg
	dia -e tietokantakaavio.svg tietokantakaavio.dia
	convert tietokantakaavio.svg tietokantakaavio.pdf
	rm tietokantakaavio.svg
